<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1608906329677' stop='1608906389695'>
    <name>My Login application</name>
    <title>My Login application</title>
    <test-cases>
        <test-case start='1608906329678' status='broken' stop='1608906389689'>
            <name>should login with valid credentials</name>
            <title>should login with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-87.0.4280.88'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "My Login application should login with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts.html). (C:\Users\Shubham Goel\Desktop\LearningProject\test\specs\example.e2e.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "My Login application should login with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts.html). (C:\Users\Shubham Goel\Desktop\LearningProject\test\specs\example.e2e.js)
                    at Test.Runnable._timeoutError (C:\Users\Shubham Goel\Desktop\LearningProject\node_modules\mocha\lib\runnable.js:432:10)
                    at Timeout.&lt;anonymous> (C:\Users\Shubham Goel\Desktop\LearningProject\node_modules\mocha\lib\runnable.js:244:24)
                    at listOnTimeout (internal/timers.js:549:17)
                    at processTimers (internal/timers.js:492:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>